#!/bin/bash
login="$USER"
file="/etc/passwd"
if [[ "$1" == "-f" ]] then
    file="$2"
    if [[ -n "$3" ]] then 
        login="$3"
    fi
elif [[ -n "$1" ]] then
    file="/etc/passwd"
    login="$1"
fi
if [[ -e "$file" ]] then
    grep -E "^$login(:)" "$file" >/dev/null 2>&2
    if [[ "$?" != 0 ]] then
       echo "User $login is not found">&2
       exit 1
    else
       echo $(grep -E "^$login(:)" "$file" | awk -F":" '{print $7}')
       exit 0
    fi
else
    echo "File $file doesn't exist">&2
    exit 2
fi
