#!/bin/bash
login="$USER"
file="/etc/passwd"
if [[ "$1" == "-f" ]] then
    file="$2"
    if [[ -n "$3" ]] then 
        login="$3"
    fi
elif [[ -n "$1" ]] then
    file="/etc/passwd"
    login="$1"
fi
grep "$file" "$login"  >/dev/null 2>&1
if [[ "$?" == 2 ]] then
    echo "File $file is not found">&2
    exit 2
elif [[ "$?" == 1 ]] then
    echo "User $login is not found">&2
    exit 1
else
    echo $(grep "$login" "$file" | cut -d ":" -f 6)
    exit 0
fi
